<?php
echo "<hr>";
    echo '<div class="col-md-8">';
    echo '<form class="form-horizontal" id="usuario_inf" action="">';
      echo '<div class="form-group">';
        echo '<label for="user_ci" class="col-sm-2 control-label">Cédula</label>';
        echo '<div class="col-sm-10">';
          echo '<input type="text" class="form-control readonly" id="user_ci" name="user_ci" placeholder="Cédula" value="'.$col_id.'">';
        echo '</div>';
      echo '</div>';
      echo '<div class="form-group">';
        echo '<button type="button" name = "rest_pass" id = "rest_pass">Restablecer ContraseÃ±a</button>';
      echo '</div>';
      echo '<div class="form-group">';
        echo '<label for="user_nombre" class="col-sm-2 control-label">Nombre</label>';
        echo '<div class="col-sm-10">';
          echo '<input type="text" class="form-control" id="user_nombre" name="user_nombre" placeholder="Nombre" value="'.$col_nombre.'">';
        echo '</div>';
      echo '</div>';
      echo '<div class="form-group">';
        echo '<label for="user_correo" class="col-sm-2 control-label">Correo Electrónico</label>';
        echo '<div class="col-sm-10">';
          echo '<input type="email" class="form-control" id="user_correo" name="user_correo" placeholder="Correo Electrónico" value="'.$col_correo.'">';
        echo '</div>';
      echo '</div>';
      echo '<div class="form-group">';
        echo '<label for="user_estado" class="col-sm-2 control-label">Estado</label>';
        echo '<div class="col-sm-10">';
        echo '<label class="switch">';
          echo '<input type="checkbox" '.($col_estado == 1? "checked" : "").' name="user_estado" id="user_estado">';
          echo '<div class="slider round"></div>';
        echo '</label>';
          echo '<input type="text" class="form-control" id="user_estado" name="user_estado" placeholder="Estado" value="'.$col_estado.'">';
        echo '</div>';
      echo '</div>';
      echo '<div class="form-group">';
        echo '<label for="user_fec_nac" class="col-sm-2 control-label">Fecha Nacimiento</label>';
        echo '<div class="col-sm-10">';
          echo '<input type="date" class="form-control" id="user_fec_nac" name="user_fec_nac" placeholder="Fecha de Nacimiento" value="'.$col_fecha_nac.'">';
        echo '</div>';
      echo '</div>';
      echo '<div class="form-group">';
        echo '<button id="guardar">Guardar</button>';
      echo '</div>';
      echo '</div>';
    echo '</form>';
    echo '</div>';
    echo '<div class="col-md-4">';
      echo '<img src="../Imagenes/'.$col_organizacion.'.jpg" alt="Logo Institución Usuario">';
    echo '</div>';
?>
